"""empty message

Revision ID: 00e7e5125ed2
Revises: 52976ce6c77b
Create Date: 2025-05-27 13:09:44.192167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e7e5125ed2'
down_revision: Union[str, None] = '52976ce6c77b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'entity_city', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entity_city', type_='unique')
    # ### end Alembic commands ###
