services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'weather'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      # POSTGRES_PORT: 5432
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/Dockerfile
    # working_dir: /src
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      PYTHONPATH: /src
      DB_USER: 'postgres'
      DB_NAME: 'weather'
      DB_PASSWORD: 'postgres'
      DB_PORT: 5432
      DB_HOST: db
      OPENMETEO_URL: 'https://api.open-meteo.com/v1/forecast'
      OPENSTREETMAP_URL: 'https://nominatim.openstreetmap.org/search'
      REDIS_URL: 'redis://localhost:6379/0'
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

volumes:
  redis_data:
  db: